import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "node:module";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Copy PDF.js worker to output directory (same folder as main.js)
const copyPdfWorker = {
	name: 'copy-pdf-worker',
	setup(build) {
		build.onEnd(() => {
			// pdfjs-dist@2.x ships classic workers as .js (better compatibility with older Electron)
			const candidates = [
				path.resolve('node_modules', 'pdfjs-dist', 'build', 'pdf.worker.min.js'),
				path.resolve('node_modules', 'pdfjs-dist', 'build', 'pdf.worker.js'),
			];
			const workerDest = path.resolve('pdf.worker.js');
			const workerSrc = candidates.find(p => fs.existsSync(p));

			if (!workerSrc) {
				console.warn('[copy-pdf-worker] Could not find pdf.worker(.min).js in pdfjs-dist');
				return;
			}

			try {
				fs.copyFileSync(workerSrc, workerDest);
				console.log('[copy-pdf-worker] Copied', workerSrc, '->', workerDest);
			} catch (e) {
				console.warn('[copy-pdf-worker] Failed to copy worker:', e);
			}
		});
	}
};

// Patch out pdfjs-dist's fake-worker `loadScript` helper, which injects a
// <script> element to fetch the worker dynamically. This plugin always supplies
// a real worker via blob URL, so that fallback path is never taken. Dynamic
// <script> injection is disallowed by Obsidian's plugin guidelines and is
// flagged by the automated review, so we replace the helper with a rejection.
// The build fails loudly if the expected pattern is absent (e.g. after a pdfjs
// upgrade), so the offending code can never silently slip back into the bundle.
const stripPdfjsLoadScript = {
	name: 'strip-pdfjs-load-script',
	setup(build) {
		build.onLoad({ filter: /pdfjs-dist[\\/]build[\\/]pdf\.js$/ }, (args) => {
			const original = fs.readFileSync(args.path, 'utf8');

			// 1. Replace `loadScript`, which injected a <script> element.
			const loadScriptReplacement =
`function loadScript(src, removeScriptElement = false) {
  // Patched at build time (esbuild.config.mjs): upstream injected a <script>
  // element to load the fake worker. We always supply a real worker, so reject.
  return Promise.reject(new Error("pdf-commenter: dynamic script loading is disabled"));
}`;
			let patched = original.replace(
				/function loadScript\(src, removeScriptElement = false\) \{[\s\S]*?\n\}/,
				loadScriptReplacement
			);
			if (patched === original) {
				throw new Error('[strip-pdfjs-load-script] loadScript pattern not found; pdfjs source may have changed');
			}

			// 2. Remove the Node fake-worker branch that calls eval("require").
			// Same dead fallback; never reached because a real worker is always supplied.
			const evalBranch =
`      if (_is_node.isNodeJS && typeof require === "function") {
        const worker = eval("require")(this.workerSrc);
        return worker.WorkerMessageHandler;
      }
`;
			if (!patched.includes(evalBranch)) {
				throw new Error('[strip-pdfjs-load-script] eval("require") branch not found; pdfjs source may have changed');
			}
			patched = patched.replace(evalBranch, '');

			if (/createElement\(["']script["']\)/.test(patched)) {
				throw new Error('[strip-pdfjs-load-script] script-element creation still present after patch');
			}
			if (/\beval\(/.test(patched)) {
				throw new Error('[strip-pdfjs-load-script] eval( still present after patch');
			}
			return { contents: patched, loader: 'js' };
		});
	}
};

// Inline the PDF.js worker code as a virtual module so the plugin is self-contained.
// This is critical for BRAT installs where only main.js/manifest.json/styles.css are downloaded.
const inlinePdfWorker = {
	name: 'inline-pdf-worker',
	setup(build) {
		build.onResolve({ filter: /^virtual:pdf-worker$/ }, () => ({
			path: 'pdf-worker',
			namespace: 'inline-worker',
		}));
		build.onLoad({ filter: /.*/, namespace: 'inline-worker' }, () => {
			const candidates = [
				path.resolve('node_modules', 'pdfjs-dist', 'build', 'pdf.worker.min.js'),
				path.resolve('node_modules', 'pdfjs-dist', 'build', 'pdf.worker.js'),
			];
			const src = candidates.find(p => fs.existsSync(p));
			if (!src) throw new Error('[inline-pdf-worker] Could not find pdf.worker(.min).js');
			const code = fs.readFileSync(src, 'utf8');
			return {
				contents: `export default ${JSON.stringify(code)};`,
				loader: 'js',
			};
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [stripPdfjsLoadScript, copyPdfWorker, inlinePdfWorker],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
